import { Property } from "./property";

export const DUMMY_PROPERTIES: Property[] = [
  {
    id: "1",
    title: "Kadıköy'de Deniz Manzaralı 3+1 Daire",
    description: "Moda sahiline yürüme mesafesinde, yenilenmiş...",
    price: 4500000,
    currency: "TRY",
    propertyType: "apartment",
    listingType: "sale",
    location: { city: "İstanbul", district: "Kadıköy" },
    details: { area: 145, roomCount: "3+1", floor: 5 },
    images: ["https://picsum.photos/seed/prop1/400/300"],
    createdAt: new Date("2024-01-15"),
    viewCount: 1250,
  },
  {
    id: "2",
    title: "Çankaya'da Bahçeli Müstakil Villa",
    description: "600 m² bahçe içinde, 5 odalı müstakil villa...",
    price: 12000000,
    currency: "TRY",
    propertyType: "villa",
    listingType: "sale",
    location: { city: "Ankara", district: "Çankaya" },
    details: { area: 320, roomCount: "5+2" },
    images: ["https://picsum.photos/seed/prop2/400/300"],
    createdAt: new Date("2024-02-01"),
    viewCount: 890,
  },
  {
    id: "3",
    title: "Alsancak'ta Kiralık Stüdyo Daire",
    description: "Merkezi konumda, eşyalı, yeni bina...",
    price: 18000,
    currency: "TRY",
    propertyType: "apartment",
    listingType: "rent",
    location: { city: "İzmir", district: "Konak" },
    details: { area: 55, roomCount: "1+0", floor: 8 },
    images: ["https://picsum.photos/seed/prop3/400/300"],
    createdAt: new Date("2024-02-10"),
    viewCount: 2100,
  },
  {
    id: "4",
    title: "Beşiktaş'ta Yatırımlık 2+1 Daire",
    description: "Merkezi lokasyon, metro yakını, yüksek kira getirisi...",
    price: 3200000,
    currency: "TRY",
    propertyType: "apartment",
    listingType: "sale",
    location: { city: "İstanbul", district: "Beşiktaş" },
    details: { area: 95, roomCount: "2+1", floor: 3 },
    images: ["https://picsum.photos/seed/prop4/400/300"],
    createdAt: new Date("2024-02-15"),
    viewCount: 1780,
  },
  {
    id: "5",
    title: "Antalya Konyaaltı'nda Satılık Arsa",
    description: "Denize 500 metre, imarlı arsa...",
    price: 8500000,
    currency: "TRY",
    propertyType: "land",
    listingType: "sale",
    location: { city: "Antalya", district: "Konyaaltı" },
    details: { area: 1200, roomCount: "-" },
    images: ["https://picsum.photos/seed/prop5/400/300"],
    createdAt: new Date("2024-03-01"),
    viewCount: 650,
  },
  {
    id: "6",
    title: "Ataşehir'de Kiralık 4+1 Rezidans",
    description: "Havuzlu site, güvenlikli, eşyalı...",
    price: 45000,
    currency: "TRY",
    propertyType: "apartment",
    listingType: "rent",
    location: { city: "İstanbul", district: "Ataşehir" },
    details: { area: 180, roomCount: "4+1", floor: 12 },
    images: ["https://picsum.photos/seed/prop6/400/300"],
    createdAt: new Date("2024-03-05"),
    viewCount: 920,
  },
];
